const Courier = {
  Amazon: 'AMAZON',
  AmazonTransportService: 'AmazonTransportService',
  Aramex: 'Aramex',
  BlueDart: 'BlueDart',
  ClickPost: 'ClickPost',
  Delhivery: 'Delhivery',
  DotZot: 'DotZot',
  DTDC: 'DTDC',
  Dunzo: 'Dunzo',
  EcomExpress: 'Ecom Express',
  Ekart: 'EKART',
  Fedex: 'Fedex',
  GrowSimplee: 'Grow Simplee',
  IndiaPost: 'India Post',
  NONE: 'None',
  PharmEasy: 'pharmeasy',
  Pickrr: 'Pickrr',
  PicoXpress: 'Pico Xpress',
  ShadowFax: 'ShadowFax',
  ShipRocket: 'ShipRocket',
  Shipway: 'Shipway',
  Smartr: 'Smartr',
  XpressBees: 'XpressBees',
  ZFW: 'ZFW',
} as const;

export { Courier };
