declare const Courier: {
    readonly ClickPost: "ClickPost";
    readonly EcomExpress: "Ecom Express";
    readonly Pickrr: "Pickrr";
    readonly BlueDart: "BlueDart";
    readonly Delhivery: "Delhivery";
    readonly Ekart: "EKART";
    readonly GrowSimplee: "Grow Simplee";
    readonly AmazonTransportService: "AmazonTransportService";
    readonly Smartr: "Smartr";
    readonly Fedex: "Fedex";
    readonly Aramex: "Aramex";
    readonly XpressBees: "XpressBees";
    readonly Amazon: "AMAZON";
    readonly IndiaPost: "India Post";
    readonly DotZot: "DotZot";
    readonly NONE: "None";
    readonly Shipway: "Shipway";
    readonly Dunzo: "Dunzo";
    readonly ShadowFax: "ShadowFax";
    readonly ZFW: "ZFW";
    readonly DTDC: "DTDC";
    readonly ShipRocket: "ShipRocket";
    readonly PharmEasy: "pharmeasy";
};
export { Courier };
