const Courier = {
  ClickPost: 'ClickPost',
  EcomExpress: 'Ecom Express',
  Pickrr: 'Pickrr',
  BlueDart: 'BlueDart',
  Delhivery: 'Delhivery',
  Ekart: 'EKART',
  GrowSimplee: 'Grow Simplee',
  AmazonTransportService: 'AmazonTransportService',
  Smartr: 'Smartr',
  Fedex: 'Fedex',
  Aramex: 'Aramex',
  XpressBees: 'XpressBees',
  Amazon: 'AMAZON',
  IndiaPost: 'India Post',
  DotZot: 'DotZot',
  NONE: 'None',
  Shipway: 'Shipway',
  Dunzo: 'Dunzo',
  ShadowFax: 'ShadowFax',
  ZFW: 'ZFW',
  DTDC: 'DTDC',
  ShipRocket: 'ShipRocket',
  PharmEasy: 'pharmeasy',
} as const;

export { Courier };
